### ISSUE TITLE
Caching of dependencies isn't working as desired

### ISSUE THREAD

**Issue by mgwelch** [johnsoncontrols/metasys-server-api-docs#8]
We can see from the build log that a cache is restored, but then there is a step that removed the node_modules directory prior to running the build.

**Comment by mgwelch** [comment]
This apparently is because of a `ci` feature: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support

Since we have a package-lock.json file it blows away node_modules.

**Comment by ConnorChristie** [comment]
Fixed after switching to circle ci
